networks:
  flask-app-network:

volumes:
  flask-app-volume:

services:
  flask-app:
    build: .
    ports:
     - 5000:5000 
    networks:
      - flask-app-network
  
  postgres:
    image: postgres:16.2
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=123456 
    networks:
      - flask-app-network
    volumes:
      - flask-app-volume:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin
    ports:
     - 8080:8080
    environment: 
     - PGADMIN_DEFAULT_EMAIL=a@a.com
     - PGADMIN_DEFAULT_PASSWORD=123456
     - PGADMIN_LISTEN_PORT=8080 

    networks:
      - flask-app-network